name: Docker

on:
  push:
    # Publish `v1.2.3` tags as releases.
    tags:
      - 'v*'

env:
  # TODO: Change variable to your image's name.
  image_name: michaelin/github-cli

jobs:
  push:
    # Ensure test job passes before pushing image.
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      
      - name: User git tag as version number
        run: |
          # Use tag as version is it starts with
          tag_prefix="refs/tags/"
          
          # Strip git ref prefix from version
          ref=${{ github.ref }}
          version="${ref#$tag_prefix}"
            
          tag=$version
          cli_version=$version
          
          # Export to environment
          echo tag=$tag >> $GITHUB_ENV
          echo cli_version=$cli_version >> $GITHUB_ENV
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push image to Docker hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.image_name }}:${{ env.tag }},${{ env.image_name }}:latest
          build-args: |
            cli_version=${{ env.cli_version }}
